-- ==========================================
-- RESTAURANT MANAGEMENT SYSTEM - TESTING SUITE
-- ==========================================


-- ==========================================
-- SECTION 1: BASIC DATA RETRIEVAL & SEARCH
-- ==========================================

-- 1.1 Search Customer Information by Name or Phone
SELECT customer_id, name, phone, email, address
FROM Customer
WHERE name LIKE '%Rahman%' OR phone LIKE '%017%';

-- 1.2 Find Active Dishes in a Specific Category
SELECT f.food_id, f.food_name, c.category_name, f.price
FROM Food f
JOIN Category c ON f.category_id = c.category_id
WHERE c.category_name = 'Main Course' 
  AND f.availability = 1;

-- 1.3 Find Low Stock Ingredients Needing Reorder
SELECT i.ingredient_id, i.ingredient_name, inv.quantity_in_stock, i.reorder_level, b.branch_name
FROM Inventory inv
JOIN Ingredient i ON inv.ingredient_id = i.ingredient_id
JOIN Branch b ON inv.branch_id = b.branch_id
WHERE inv.quantity_in_stock <= i.reorder_level;


-- ==========================================
-- SECTION 2: CALCULATIONS & AGGREGATIONS
-- ==========================================

-- 2.1 Calculate Total Payroll Expenses per Branch
SELECT b.branch_name, COUNT(e.employee_id) AS total_employees, SUM(e.salary) AS total_monthly_salary
FROM Branch b
LEFT JOIN Employee e ON b.branch_id = e.branch_id
WHERE e.employment_status = 'Active'
GROUP BY b.branch_name
ORDER BY total_monthly_salary DESC;

-- 2.2 Find Best-Selling Food Items by Order Volume
SELECT f.food_name, SUM(oi.quantity) AS total_units_sold, SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM OrderItem oi
JOIN Food f ON oi.food_id = f.food_id
GROUP BY f.food_name
ORDER BY total_units_sold DESC;

-- 2.3 Calculate Total Sales Revenue Generated by Each Branch
SELECT b.branch_name, COUNT(o.order_id) AS total_orders, SUM(o.total_amount) AS total_revenue
FROM Orders o
JOIN Branch b ON o.branch_id = b.branch_id
WHERE o.order_status = 'completed'
GROUP BY b.branch_name
ORDER BY total_revenue DESC;


-- ==========================================
-- SECTION 3: JOINS & MULTI-TABLE RELATIONSHIPS
-- ==========================================

-- 3.1 Find Suppliers and the Ingredients They Supply (With Prices)
SELECT s.supplier_name, i.ingredient_name, si.supply_price, i.unit
FROM Supplier s
JOIN Supplier_Ingredient si ON s.supplier_id = si.supplier_id
JOIN Ingredient i ON si.ingredient_id = i.ingredient_id
ORDER BY s.supplier_name;

-- 3.2 Retrieve Full Details of an Order (Customer, Employee, & Line Items)
SELECT o.order_id, c.name AS customer_name, e.name AS employee_name, 
       f.food_name, oi.quantity, oi.unit_price, (oi.quantity * oi.unit_price) AS subtotal
FROM Orders o
LEFT JOIN Customer c ON o.customer_id = c.customer_id
JOIN Employee e ON o.employee_id = e.employee_id
JOIN OrderItem oi ON o.order_id = oi.order_id
JOIN Food f ON oi.food_id = f.food_id
WHERE o.order_id = 1;


-- ==========================================
-- SECTION 4: TRIGGER TESTING & VERIFICATION
-- ==========================================

-- 4.1 Test Auto-updating Order Total (`OrderItem_UpdateOrderTotal`)

-- Step A: Check current order total
SELECT order_id, total_amount FROM Orders WHERE order_id = 1;

-- Step B: Insert an item into the order
INSERT INTO OrderItem (order_id, food_id, quantity, unit_price)
VALUES (1, 1, 2, 672.20);

-- Step C: Verify updated order total
SELECT order_id, total_amount FROM Orders WHERE order_id = 1;


-- 4.2 Test Inventory Restocking on Cancellation (`Orders_RestockOnCancel`)

-- Step A: Check stock for an ingredient
SELECT * FROM Inventory WHERE branch_id = 1 AND ingredient_id = 19;

-- Step B: Cancel an active order
UPDATE Orders
SET order_status = 'cancelled'
WHERE order_id = 1;

-- Step C: Verify stock is replenished
SELECT * FROM Inventory WHERE branch_id = 1 AND ingredient_id = 19;